# CAS BACnet Stack network type
NETWORK_TYPE_IP = 0
NETWORK_TYPE_MSTP = 1

# General constants
NETWORK_PORT_LOWEST_PROTOCOL_LAYER = 4194303

# Object types
OBJECT_TYPE_ANALOG_INPUT = 0
OBJECT_TYPE_ANALOG_OUTPUT = 1
OBJECT_TYPE_ANALOG_VALUE = 2
OBJECT_TYPE_BINARY_INPUT = 3
OBJECT_TYPE_BINARY_OUTPUT = 4
OBJECT_TYPE_BINARY_VALUE = 5
OBJECT_TYPE_DEVICE = 8
OBJECT_TYPE_MULTI_STATE_INPUT = 13
OBJECT_TYPE_MULTI_STATE_OUTPUT = 14
OBJECT_TYPE_MULTI_STATE_VALUE = 19
OBJECT_TYPE_TREND_LOG = 20
OBJECT_TYPE_BITSTRING_VALUE = 39
OBJECT_TYPE_CHARACTERSTRING_VALUE = 40
OBJECT_TYPE_DATE_VALUE = 42
OBJECT_TYPE_INTEGER_VALUE = 45
OBJECT_TYPE_LARGE_ANALOG_VALUE = 46
OBJECT_TYPE_OCTETSTRING_VALUE = 47
OBJECT_TYPE_POSITIVE_INTEGER_VALUE = 48
OBJECT_TYPE_TIME_VALUE = 50
OBJECT_TYPE_NETWORK_PORT = 56
OBJECT_TYPE_ELEVATOR_GROUP = 57
OBJECT_TYPE_ESCALATOR = 58
OBJECT_TYPE_LIFT = 59
PROPERTY_IDENTIFIER_ALL = 8
PROPERTY_IDENTIFIER_COV_INCURMENT = 22
PROPERTY_IDENTIFIER_DAY_LIGHT_SAVINGS_STATUS = 24
PROPERTY_IDENTIFIER_DESCRIPTION = 28
PROPERTY_IDENTIFIER_LOCAL_DATE = 56
PROPERTY_IDENTIFIER_LOCAL_TIME = 57
PROPERTY_IDENTIFIER_NUMBER_OF_STATES = 74
PROPERTY_IDENTIFIER_OBJECT_NAME = 77
PROPERTY_IDENTIFIER_PRESENT_VALUE = 85
PROPERTY_IDENTIFIER_PRIORITY_ARRAY = 87
PROPERTY_IDENTIFIER_RELIABILITY = 103
PROPERTY_IDENTIFIER_STATE_TEXT = 110
PROPERTY_IDENTIFIER_STATUS_FLAGS = 111
PROPERTY_IDENTIFIER_SYSTEM_STATUS = 112
PROPERTY_IDENTIFIER_UTC_OFFSET = 119
PROPERTY_IDENTIFIER_BIT_TEXT = 343
PROPERTY_IDENTIFIER_MAX_PRES_VALUE = 65
PROPERTY_IDENTIFIER_MIN_PRES_VALUE = 69


# Network property identifiers
PROPERTY_IDENTIFIER_IP_ADDRESS = 400
PROPERTY_IDENTIFIER_IP_DEFAULT_GATEWAY = 401
PROPERTY_IDENTIFIER_IP_DNS_SERVER = 406
PROPERTY_IDENTIFIER_IP_SUBNET_MASK = 411
PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT = 412
PROPERTY_IDENTIFIER_LINK_SPEED = 420
PROPERTY_IDENTIFIER_MAC_ADDRESS = 423

# Services supported
SERVICE_SUBSCRIBE_COV = 5
SERVICE_CREATE_OBJECT = 10
SERVICE_DELETE_OBJECT = 11
SERVICE_READ_PROPERTY_MULTIPLE = 14
SERVICE_WRITE_PROPERTY = 15
SERVICE_WRITE_PROPERTY_MULTIPLE = 16
SERVICE_I_AM = 26
SERVICE_I_HAVE = 27
SERVICE_TIME_SYNCHRONIZATION = 32
SERVICE_READ_RANGE = 35
SERVICE_UTC_TIME_SYNCHRONIZATION = 36
SERVICE_SUBSCRIBE_COV_PROPERTY = 38
SERVICE_WHO_HAS = 33
SERVICE_WHO_IS = 34

# Error codes
ERROR_NO_SPACE_TO_WRITE_PROPERTY = 20
ERROR_VALUE_OUT_OF_RANGE = 37
NETWORK_TYPE_IPV4 = 5
PROTOCOL_LEVEL_BACNET_APPLICATION = 2

# Priority array
MAX_BACNET_PRIORITY = 16

# Trend log buffer type
MAX_TREND_LOG_MAX_BUFFER_SIZE = 100

# Data types
DATA_TYPE_NULL = 0
DATA_TYPE_BOOLEAN = 1
DATA_TYPE_UNSIGNED_INTEGER = 2
DATA_TYPE_SIGNED_INTEGER = 3
DATA_TYPE_REAL = 4
DATA_TYPE_DOUBLE = 5
DATA_TYPE_OCTET_STRING = 6
DATA_TYPE_CHARACTER_STRING = 7
DATA_TYPE_BIT_STRING = 8
DATA_TYPE_ENUMERATED = 9
DATA_TYPE_DATE = 10
DATA_TYPE_TIME = 11
DATA_TYPE_BACNET_OBJECT_IDENTIFIER = 1


